networks:
  default:
    name: traefik_default
    external: true

services:
  whoami:
    image: traefik/whoami
    restart: "always"
    expose:
      - 80
    labels:
      - "proxy=internal"
      - "traefik.enable=true"

      - "traefik.http.routers.whoami.rule=Path(`/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=http"