networks:
  default:
    name: traefik_default
    external: true

services:
  whoami:
    image: traefik/whoami
    restart: "always"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Path(`/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=internal"
      - "traefik.http.routers.whoami.tls=true"