# static yaml
log:
  level: DEBUG

accesslog:
  addInternals: true

api:
  dashboard: true
  debug: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
  internal:
    address: ":81"

serversTransport:
  insecureSkipVerify: true

providers:
  file:
    filename: dynamic.yml
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    constraints: Label(`proxy`, `external`)