# dynamic yaml

http:
  routers:
    allowed:
      entryPoints:
        - https
      rule: "(ClientIP(`127.0.0.0/24`) || ClientIP(`192.168.0.16/32`))"
      service: internal
      priority: 10
    fallback:
      entryPoints:
        - https
      rule: "ClientIP(`0.0.0.0/0`)"
      service: internal
      middlewares:
        - basic-auth
      priority: 1
  
  services:
    internal:
      loadBalancer:
        servers:
          - url: "http://proxy:81"
            preservePath: true

  middlewares:
    basic-auth:
      basicAuth:
        users:
          - "admin:$2y$12$kojSmwwx6PiAm3Vjtn5KtOLilpwaPSl5XwXL.PSakG79Rs3qVuzGq"

tls:
  certificates:
    - certFile: /certs/local-cert.pem
      keyFile: /certs/local-key.pem
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: /certs/local-cert.pem
        keyFile: /certs/local-key.pem