# static yaml
log:
  level: DEBUG

accesslog:
  addInternals: true

api:
  dashboard: true
  debug: true

entryPoints:
  http:
    address: ":80"

serversTransport:
  insecureSkipVerify: true

providers:
  file:
    filename: dynamic.yml
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    constraints: Label(`proxy`, `internal`)